
export const FEATURES = {
    // Admin Charts
    payouts_pie_chart: {
        "id": "payouts_pie_chart",
        "name": "Payout Stats",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCharts",
        "endpoint": '/api/admin/earning-reports/payout-stats',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "DashBoard Statictics",
    },
    payments_pie_chart: {
        "id": "payments_pie_chart",
        "name": "Payments grants and dues",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCharts",
        "endpoint": '/api/admin/payments/stats',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "DashBoard Statictics",
    },
    payments_line_chart: {
        "id": "payments_line_chart",
        "name": "Daily Payments",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCharts",
        "endpoint": '/api/admin/payments/daily-spikes',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "DashBoard Statictics",
    },
    enrollments_line_chart: {
        "id": "enrollments_line_chart",
        "name": "Daily Enrollments",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCharts",
        "endpoint": '/api/admin/enrollments/daily-spikes',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "DashBoard Statictics",

    },
    clicks_line_chart: {
        "id": "clicks_line_chart",
        "name": "Daily Earnings",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCharts",
        "endpoint": '/api/admin/earning-reports/daily-spikes',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "DashBoard Statictics",

    },

    // User management
    user_management: {
        "id": "user_management",
        "name": "User Management",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": null,
        "HTTPMethod": null,
        "parent": null,
        "featureGroup": "User Management",
    },
    students: {
        "id": "students",
        "name": "Students",
        "frontendUrl": '/admin/students',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/users/students',
        "HTTPMethod": 'get',
        "parent": 'user_management',
        "featureGroup": "User Management",

    },
    admins: {
        "id": "admins",
        "name": "Admins",
        "frontendUrl": '/admin/admins',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/users/admins',
        "HTTPMethod": 'get',
        "parent": 'user_management',
        "featureGroup": "User Management",
    },
    instructors: {
        "id": "instructors",
        "name": "Instructors",
        "frontendUrl": '/admin/instructors',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/users/instructors',
        "HTTPMethod": 'get',
        "parent": 'user_management',
        "featureGroup": "User Management",
    },
    create_user: {
        "id": "create_user",
        "name": "Add User",
        "frontendUrl": null,
        "frontendSectionGroup": "userManagementModule",
        "endpoint": '/api/admin/users',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "User Management",
    },
    update_user: {
        "id": "update_user",
        "name": "Update User",
        "frontendUrl": null,
        "frontendSectionGroup": "userManagementModule",
        "endpoint": '/api/admin/users/by-user-id/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "User Management",

        // todo - assign feature group
    },
    get_kyc_documents_of_a_user: {
        "id": "get_kyc_documents_of_a_user",
        "name": "KYC documents",
        "frontendUrl": null,
        "frontendSectionGroup": "userManagementModule",
        "endpoint": '/api/admin/users/:userId/kyc-documents',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "User Management",
    },

    get_user_by_id: {
        "id": "get_user_by_id",
        "name": "Get User Details",
        "frontendUrl": null,
        "frontendSectionGroup": "userManagementModule",
        "endpoint": '/api/admin/users/by-user-id/:id',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",
    },

    user_select: {
        "id": "user_select",
        "name": "Search User",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGenericModule",
        "endpoint": '/api/admin/users/search/:searchTerm',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",

    },
    user_selected: {
        "id": "user_selected",
        "name": "Selected Users",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGenericModule",
        "endpoint": '/api/admin/users/selected',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",

    },

    // Courses
    course_management: {
        "id": "course_management",
        "name": "Course Management",
        "frontendUrl": '/admin/courses',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": null,
        "HTTPMethod": null,
        "parent": null,
        "featureGroup": "Course Management",

    },
    courses: {
        "id": "courses",
        "name": "Courses",
        "frontendUrl": '/admin/courses',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/courses',
        "HTTPMethod": 'get',
        "parent": 'course_management',
        "featureGroup": "Course Management",

    },
    create_course: {
        "id": "create_course",
        "name": "Create Course",
        "frontendUrl": '/admin/create-course',
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Course Management",

    },


    update_course: {
        "id": "update_course",
        "name": "Update Course",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Course Management",

    },
    delete_course: {
        "id": "delete_course",
        "name": "Delete Course",
        "frontendUrl": '/admin/create-course',
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Course Management",

    },
    course_categories: {
        "id": "course_categories",
        "name": "Course Categories",
        "frontendUrl": '/admin/course-categories',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": null,
        "HTTPMethod": null,
        "parent": 'course_management',
        "featureGroup": "Course Management",

    },
    create_course_category: {
        "id": "create_course_category",
        "name": "Create Category",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseCategoryModule",
        "endpoint": '/api/admin/categories',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Course Management",

    },
    update_course_category: {
        "id": "update_course_category",
        "name": "Update Category",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseCategoryModule",
        "endpoint": '/api/admin/categories/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Course Management",

    },
    delete_course_category: {
        "id": "delete_course_category",
        "name": "Delete Category",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseCategoryModule",
        "endpoint": '/api/admin/categories/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Course Management",

    },

    create_lesson: {
        "id": "create_lesson",
        "name": "Course Lesson",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/lesson',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Course Content",

    },
    update_lesson: {
        "id": "update_lesson",
        "name": "Update Lesson",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/lesson/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Course Content",

    },
    delete_lesson: {
        "id": "delete_lesson",
        "name": "Delte Lesson",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/lesson/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Course Content",

    },
    create_section: {

        "id": "create_section",
        "name": "Course Section",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/section',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Course Content",
    },
    update_section: {
        "id": "update_section",
        "name": "Update Section",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/section/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Course Content",

    },
    delete_section: {
        "id": "delete_section",
        "name": "Delete Section",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/courses/section/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Course Content",

    },
    live_class_of_a_course: {
        "id": "live_class_of_a_course",
        "name": "Live Classes",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/live-classes/:courseId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Live Class",
    },
    update_live_class: {
        "id": "update_live_class",
        "name": "Live Classes",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/live-classes',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Live Class",
    },
    delete_live_class: {
        "id": "delete_live_class",
        "name": "Delete Live Class",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCourseModule",
        "endpoint": '/api/admin/live-classes/:courseId',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Live Class",
    },
    // go_live: {
    //     "id": "go_live",
    //     "name": "Go Live",
    //     "frontendUrl": null,
    //     "frontendSectionGroup": "adminCourseModule",
    //     "endpoint": '/api/admin/live-classes/ongoing-status/:liveClassId',
    //     "HTTPMethod": 'patch',
    //     "parent": null,
    //     "featureGroup": "Live Class",
    // },

    // Pre registration
    pre_registrations: {
        "id": "pre_registrations",
        "name": "Pre Registrations",
        "frontendUrl": '/admin/pre-registrations',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/pre-registrations',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Pre registration",

    },
    download_pre_registrations_data: {
        "id": "download_pre_registrations_data",
        "name": "Download as CSV",
        "frontendUrl": '/admin/pre-registrations',
        "frontendSectionGroup": "adminPreRegistrationModule",
        "endpoint": '/api/admin/pre-registrations/download',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Pre registration",
    },
    archive_pre_registrations: {
        "id": "archive_pre_registrations",
        "name": "Archive All",
        "frontendUrl": '/admin/pre-registrations',
        "frontendSectionGroup": "adminPreRegistrationModule",
        "endpoint": '/api/admin/pre-registrations/archive-all',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Pre registration",

    },
    archive_single_pre_registration: {
        "id": "archive_single_pre_registration",
        "name": "Mark as Archive",
        "frontendUrl": '/admin/pre-registrations',
        "frontendSectionGroup": "adminPreRegistrationModule",
        "endpoint": '/api/admin/pre-registrations',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Pre registration",

    },

    // Enrollments
    enrollments: {
        "id": "enrollments",
        "name": "Enrollments",
        "frontendUrl": '/admin/enrollments',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/enrollments',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Enrollments",

    },
    create_enrollment_by_admin: {
        "id": "create_enrollment_by_admin",
        "name": "Enroll",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/enrollments',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Enrollments",
    },
    chat_signup: {
        "id": "chat_signup",
        "name": "Enroll",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments/chat-signup',
        "HTTPMethod": 'post',
        "parent": null,
        // "featureGroup": "Enrollments",
    },
    bulk_chat_signup: {
        "id": "bulk_chat_signup",
        "name": "Enroll",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments/chat-bulk-signup',
        "HTTPMethod": 'post',
        "parent": null,
        // "featureGroup": "Enrollments",
    },
    bulk_enroll: {
        "id": "bulk_enroll",
        "name": "Bulk Enroll",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments/:courseId/bulk-payment-and-enroll-from-sheet',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Enrollments",
    },

    remove_enrollment: {
        "id": "remove_enrollment",
        "name": "Remove Access",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/enrollments/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Enrollments",

    },

    // Tools
    tools_and_resources: {
        "id": "tools_and_resources",
        "name": "Tools And Resources",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": null,
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Tools And Resources",

    },
    tools: {
        "id": "tools",
        "name": "Tools",
        "frontendUrl": '/admin/tools',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/tools',
        "HTTPMethod": 'get',
        "parent": 'tools_and_resources',
        "featureGroup": "Tools And Resources",

    },
    tool_access_list: {
        "id": "tool_access_list",
        "name": "Tools Access",
        "frontendUrl": '/admin/tool-access',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/tools/access',
        "HTTPMethod": 'get',
        "parent": 'tools_and_resources',
        "featureGroup": "Tools And Resources",

    },
    tools_access_list_of_user: {
        "id": "tools_access_list_of_user",
        "name": "Tools of Users",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools/access/users/:userId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",
    },
    remove_tool_access: {
        "id": "remove_tool_access",
        "name": "Remove Tool access",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools/access/:toolId/:userId',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "User Management",
    },

    give_tools_access: {
        "id": "give_tools_access",
        "name": "Give Access",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools/access',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Tools And Resources",

    },
    give_tools_access_in_bulk: {
        "id": "give_tools_access_in_bulk",
        "name": "Give Access in Bulk",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools/bulk-access-to-all-paid-students/:courseId/:toolId',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Tools And Resources",

    },
    add_tool: {
        "id": "add_tool",
        "name": "Add Tool",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Tools And Resources",

    },
    delete_tool: {
        "id": "delete_tool",
        "name": "Delete Tool",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Tools And Resources",

    },
    update_tool: {
        "id": "update_tool",
        "name": "Update Tool",
        "frontendUrl": null,
        "frontendSectionGroup": "adminToolsModule",
        "endpoint": '/api/admin/tools',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Tools And Resources",

    },

    // Payments
    payments: {
        "id": "payments",
        "name": "Payments",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/payments',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Payments",

    },
    payment_histories: {
        "id": "payment_histories",
        "name": "Payment Histories",
        "frontendUrl": '/admin/payments',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/payments',
        "HTTPMethod": 'get',
        "parent": 'payments',
        "featureGroup": "Payments",

    },
    payment_dues: {
        "id": "payment_dues",
        "name": "Dues",
        "frontendUrl": '/admin/payment-dues',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/payments/dues',
        "HTTPMethod": 'get',
        "parent": 'payments',
        "featureGroup": "Payments",
    },
    bulk_unenroll_all_dues: {
        "id": "bulk_unenroll_all_dues",
        "name": "Unenroll due's at once",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments/:courseId/unenroll-all-students-with-deus',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Payments",
    },

    bulk_unenroll_dues_selected: {
        "id": "bulk_unenroll_dues_selected",
        "name": "Unenroll selected due's",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/enrollments/:courseId/bulk-unenroll',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Payments",
    },

    payment_dues_download: {
        "id": "payment_dues_download",
        "name": "Dues list CSV",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments/dues-download',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Payments",
    },
    download_payments: {
        "id": "download_payments",
        "name": "Download Payments History",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments/download',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Payments",

    },

    create_payment_by_admin: {
        "id": "create_payment_by_admin",
        "name": "Create Payment",
        "frontendUrl": null,
        "frontendSectionGroup": "adminPaymentModule",
        "endpoint": '/api/admin/payments',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Payments",
    },

    // Earning report
    earning_reports: {
        "id": "earning_reports",
        "name": "Earnings",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": null,
        "HTTPMethod": null,
        "parent": null,
        "featureGroup": "Earnings",

    },


    earning_reports_list: {
        "id": "earning_reports_list",
        "name": "Student's Earnings",
        "frontendUrl": '/admin/earnings',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports',
        "HTTPMethod": 'get',
        "parent": 'earning_reports',
        "featureGroup": "Earnings",

    },
    earning_reports_daily: {
        "id": "earning_reports_daily",
        "name": "Daily Report",
        "frontendUrl": '/admin/daily-earnings',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/daily',
        "HTTPMethod": 'get',
        "parent": 'earning_reports',
        "featureGroup": "Earnings",

    },
    earning_reports_users_balances: {
        "id": "earning_reports_users_balances",
        "name": "Student's Balances",
        "frontendUrl": '/admin/balances',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/balances',
        "HTTPMethod": 'get',
        "parent": 'earning_reports',
        "featureGroup": "Earnings",

    },
    balance_of_a_user: {
        "id": "balance_of_a_user",
        "name": "Balance",
        "frontendUrl": '/admin/balances/:id',
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/wallets/users/:userId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Earnings",

    },
    add_extra_click_to_shortner: {
        "id": "add_extra_click_to_shortner",
        "name": "Extra link Click",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/extra-clicks',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Earnings",
    },
    earning_report_of_a_user: {
        "id": "earning_report_of_a_user",
        "name": "Earning Report",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/users/:userId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Earnings",

    },

    smartlinks_of_a_user: {
        "id": "smartlinks_of_a_user",
        "name": "Smart Link",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/shortlinks/users/:userId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Earnings",

    },

    // Payouts
    'students_payouts': {
        "id": "students_payouts",
        "name": "Payouts",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/payouts',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Payouts",

    },
    'students_payouts_under_review': {
        "id": "students_payouts_under_review",
        "name": "Under Reviews",
        "frontendUrl": '/admin/payouts/under-reviews',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/payouts',
        "HTTPMethod": 'get',
        "parent": 'students_payouts',
        "featureGroup": "Payouts",

    },
    'students_payouts_waiting_for_payment': {
        "id": "students_payouts_waiting_for_payment",
        "name": "Waiting for payments",
        "frontendUrl": '/admin/payouts/pending',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/payouts',
        "HTTPMethod": 'get',
        "parent": 'students_payouts',
        "featureGroup": "Payouts",

    },
   
    'students_payouts_histories': {
        "id": "students_payouts_histories",
        "name": "Paid",
        "frontendUrl": '/admin/payouts/paid',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/payouts',
        "HTTPMethod": 'get',
        "parent": 'students_payouts',
        "featureGroup": "Payouts",

    },
    'students_rejected_payouts_histories': {
        "id": "students_rejected_payouts_histories",
        "name": "Rejected",
        "frontendUrl": '/admin/payouts/rejected',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/earning-reports/payouts',
        "HTTPMethod": 'get',
        "parent": 'students_payouts',
        "featureGroup": "Payouts",
    },
    update_payout_status: {
        "id": "update_payout_status",
        "name": "Update Status",
        "frontendUrl": null,
        "frontendSectionGroup": "payoutModule",
        "endpoint": '/api/admin/earning-reports/payouts/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Payouts",

    },
    update_payout_reviewer_status: {
        "id": "update_payout_reviewer_status",
        "name": "Update Review Status",
        "frontendUrl": null,
        "frontendSectionGroup": "payoutModule",
        "endpoint": '/api/admin/earning-reports/payouts/:id/review',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Payouts",

    },
    make_payout_of_a_user_by_admin: {
        "id": "make_payout_of_a_user_by_admin",
        "name": "Payouts",
        "frontendUrl": null,
        "frontendSectionGroup": "payoutModule",
        "endpoint": '/api/admin/earning-reports/payouts/users/:userId',
        "HTTPMethod": 'post',
        "parent": null,
        // todo
    },

    payouts_of_a_user: {
        "id": "payouts_of_a_user",
        "name": "Payouts of a User",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/payouts/users/:userId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",

    },
    payments_of_a_user: {
        "id": "payments_of_a_user",
        "name": "Payments of a User",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/payments/users/:userId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",
    },
    remove_payment: {
        "id": "remove_payment",
        "name": "Remove Payment",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/payments/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        // "featureGroup": "User Management",
    },
    enrollments_of_a_user: {
        "id": "enrollments_of_a_user",
        "name": "Enrollments",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/enrollments/users/:id',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "User Management",
    },


    generate_smart_link_for_user: {
        "id": "generate_smart_link_for_user",
        "name": "Genrate Smartlink",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/shortlinks',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "User Management",
    },
    change_smart_link_status: {
        "id": "change_smart_link_status",
        "name": "Smartlink Status Change",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/earning-reports/shortlinks/:shortLinkId/status',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "User Management",
    },


    // Notice
    student_portal: {
        id: 'student_portal',
        "name": "Student Portal",
        "frontendUrl": '/',
        "frontendSectionGroup": 'adminHeaderNav',
        "endpoint": null,
        "HTTPMethod": null,
        "parent": null
        // todo
    },
    notice_board: {
        id: 'notice_board',
        "name": "Notices",
        "frontendUrl": '/admin/notices',
        "frontendSectionGroup": 'adminHeaderNav',
        "endpoint": '/api/admin/notices',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Notices",

    },

    create_notice: {
        id: 'create_notice',
        "name": "Notice Histories",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "endpoint": '/api/admin/notices',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Notices",

    },

    delete_notice: {
        id: 'delete_notice',
        "name": "Delete Notice",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "endpoint": '/api/admin/notices/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Notices",
    },
    update_notice: {
        id: 'update_notice',
        "name": "Update Notice",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "endpoint": '/api/admin/notices',
        "HTTPMethod": 'patch',
        "parent": null,

        "featureGroup": "Notices",

    },
    create_notice_dept: {
        id: 'create_notice_dept',
        "name": "Create Notice Department",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "endpoint": '/api/admin/notices/departments',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Notices",

    },
    delete_notice_dpt: {
        id: 'delete_notice_dpt',
        "name": "Delete Department",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "parent": null,
        "endpoint": '/api/admin/notices/departments/:id',
        "HTTPMethod": 'delete',
        "featureGroup": "Notices",

    },
    get_notice_dpt: {
        id: 'get_notice_dpt',
        "name": "Notice Departments",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "parent": null,
        "endpoint": '/api/admin/notices/departments',
        "HTTPMethod": 'get',
        "featureGroup": "Notices",

    },
    // depricated
    // Notification - Admin notification channel
    // enrollment_updates_notification: {
    //     id: 'enrollment_updates_notification',
    //     "name": "Enrollment Updates",
    //     "frontendUrl": null,
    //     "frontendSectionGroup": 'AdminNotificationsChannel',
    //     "parent": null,
    //     "endpoint": null,
    //     "HTTPMethod": 'get',
    //     "featureGroup": "Notifications",

    // },
    // payment_updates_notification: {
    //     id: 'payment_updates_notification',
    //     "name": "Payments Updates",
    //     "frontendUrl": null,
    //     "frontendSectionGroup": 'AdminNotificationsChannel',
    //     "parent": null,
    //     "endpoint": null,
    //     "HTTPMethod": 'get',
    //     "featureGroup": "Notifications",
    // },
    all_assignment_submission_updates_notification: {
        id: 'all_assignment_submission_updates_notification',
        "name": "All Assignment Updates",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNotificationsChannel',
        "parent": null,
        "endpoint": null,
        "HTTPMethod": 'get',
        "featureGroup": "Notifications",
    },
    my_assignment_submission_updates_notification: {
        id: 'my_assignment_submission_updates_notification',
        "name": "My Assignment Updates",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNotificationsChannel',
        "parent": null,
        "endpoint": null,
        "HTTPMethod": 'get',
        "featureGroup": "Notifications",
    },
    pending_withdraw_updates_notification: {
        id: 'pending_withdraw_updates_notification',
        "name": "Pending Withdraw Updates",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNotificationsChannel',
        "parent": null,
        "endpoint": null,
        "HTTPMethod": 'get',
        "featureGroup": "Notifications",
    },
    awaiting_withdraw_updates_notification: {
        id: 'awaiting_withdraw_updates_notification',
        "name": "Awaiting Withdraw Payment Updates",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNotificationsChannel',
        "parent": null,
        "endpoint": null,
        "HTTPMethod": 'get',
        "featureGroup": "Notifications",
    },
    refund_updates_notification: {
        id: 'refund_updates_notification',
        "name": "Refund Updates",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNotificationsChannel',
        "parent": null,
        "endpoint": null,
        "HTTPMethod": 'get',
        "featureGroup": "Notifications",
    },

    // reviews 
    reviews: {
        id: 'reviews',
        "name": "Student Reviews",
        "frontendUrl": '/admin/reviews',
        "frontendSectionGroup": 'adminSidebar',
        "endpoint": '/api/admin/reviews',
        "HTTPMethod": 'get',
        "featureGroup": "Student Reviews",

    },
    update_review: {
        id: 'update_review',
        "name": "Update Review",
        "frontendUrl": null,
        "frontendSectionGroup": 'adminReviewModule',
        "endpoint": '/api/admin/reviews/:id',
        "HTTPMethod": 'patch',
        "featureGroup": "Student Reviews",

    },
    delete_review: {
        id: 'delete_review',
        "name": "Delete Review",
        "frontendUrl": null,
        "frontendSectionGroup": 'adminReviewModule',
        "endpoint": '/api/admin/reviews/:id',
        "HTTPMethod": 'delete',
        "featureGroup": "Student Reviews",

    },
    // Notification 
    admin_notifications: {
        id: 'admin_notifications',
        "name": "Admin Notifications",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "endpoint": '/api/admin/notifications',
        "HTTPMethod": 'get',
        "parent": null,
        // "featureGroup": "Student Reviews",
        // todo

    },
    send_notification: {
        id: 'send_notification',
        "name": "Create Notification",
        "frontendUrl": null,
        "frontendSectionGroup": 'AdminNoticeBoardModule',
        "endpoint": '/api/admin/notifications',
        "HTTPMethod": 'post',
        "parent": null,
        // "featureGroup": "Student Reviews",
        // todo

    },
    // Blogs
    blogs: {
        "id": "blogs",
        "name": "Blogs",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": null,
        "HTTPMethod": null,
        "parent": null,
        "featureGroup": "Blogs",

    },
    blog_posts: {
        "id": "blog_posts",
        "name": "Posts",
        "frontendUrl": "/admin/posts",
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/blogs',
        "HTTPMethod": "get",
        "parent": 'blogs',
        "featureGroup": "Blogs",

    },
    blog_categories: {
        "id": "blog_categories",
        "name": "Blog Categories",
        "frontendUrl": "/admin/posts-categories",
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/blogs/categories',
        "HTTPMethod": "get",
        "parent": 'blogs',
        "featureGroup": "Blogs",
    },
    blog_category_create: {
        "id": "blog_category_create",
        "name": "Create Blog Category",
        "frontendUrl": "/admin/posts-categories",
        "frontendSectionGroup": "blogModule",
        "endpoint": '/api/admin/blogs/categories',
        "HTTPMethod": "post",
        "parent": 'null',
        "featureGroup": "Blogs",
    },
    blog_category_delete: {
        "id": "blog_category_delete",
        "name": "Remove Blog Category",
        "frontendUrl": null,
        "frontendSectionGroup": "blogModule",
        "endpoint": '/api/admin/blogs/categories/:id',
        "HTTPMethod": "delete",
        "parent": null,
        "featureGroup": "Blogs",
    },
    blog_category_update: {
        "id": "blog_category_update",
        "name": "Update Blog Category",
        "frontendUrl": null,
        "frontendSectionGroup": "blogModule",
        "endpoint": '/api/admin/blogs/categories/:id',
        "HTTPMethod": "patch",
        "parent": null,
        "featureGroup": "Blogs",
    },
    blog_create: {
        "id": "blog_create",
        "name": "Create Post",
        "frontendUrl": null,
        "frontendSectionGroup": "blogModule",
        "endpoint": '/api/admin/blogs/categories',
        "HTTPMethod": "post",
        "parent": null,
        "featureGroup": "Blogs",
    },

    blog_update: {
        "id": "blog_update",
        "name": "Update Post",
        "frontendUrl": "/admin/posts/create/:id",
        "frontendSectionGroup": "blogModule",
        "endpoint": '/api/admin/blogs/:id',
        "HTTPMethod": "patch",
        "parent": null,
        "featureGroup": "Blogs",

    },
    blog_delete: {
        "id": "blog_delete",
        "name": "Delete Post",
        "frontendUrl": "",
        "frontendSectionGroup": "blogModule",
        "endpoint": '/api/admin/blogs/:id',
        "HTTPMethod": "delete",
        "parent": null,
        "featureGroup": "Blogs",

    },
    // Access control
    all_features: {
        "id": "all_features",
        "name": "All Features",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/access-control/features',
        "HTTPMethod": "get",
        "parent": null,
        // "featureGroup": "Features Access Control",
    },
    update_features_of_user: {
        "id": "update_features_of_user",
        "name": "Update User's Features",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/access-control/feature-user-map',
        "HTTPMethod": "patch",
        "parent": null,
        "featureGroup": "Features Access Control",
    },
    features_of_a_user: {
        "id": "features_of_a_user",
        "name": "User's Features",
        "frontendUrl": null,
        "frontendSectionGroup": "userModule",
        "endpoint": '/api/admin/access-control/features/users/:userId',
        "HTTPMethod": "get",
        "parent": null,
        "featureGroup": "Features Access Control",
    },

    // Student dynamic feature
    student_earning_report: {
        "id": "student_earning_report",
        "name": "আর্নিং রিপোর্ট",
        "frontendUrl": "/dashboard/earning-report",
        "frontendSectionGroup": "studentDashboardSidebar",
        "endpoint": '/api/earning-reports/my-earnings',
        "HTTPMethod": "get",
        "parent": null,
        "featureGroup": "Student Features",
    },
    student_wallet: {
        "id": "student_wallet",
        "name": "আমার ওয়ালেট",
        "frontendUrl": "/dashboard/wallet",
        "frontendSectionGroup": "studentDashboardSidebar",
        "endpoint": '/api/earning-reports/my-wallet',
        "HTTPMethod": "get",
        "parent": null,
        "featureGroup": "Student Features",

    },

    // Coupon
    coupons: {
        "id": "coupons",
        "name": "Coupons",
        "frontendUrl": '/admin/coupons',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/coupons',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Coupons",
    },
    create_coupon: {
        "id": "create_coupon",
        "name": "Create Coupon",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCouponModule",
        "endpoint": '/api/admin/coupons',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Coupons",

    },
    update_coupon: {
        "id": "update_coupon",
        "name": "Update Coupon",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCouponModule",
        "endpoint": '/api/admin/coupons/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Coupons",

    },
    delete_coupon: {
        "id": "delete_coupon",
        "name": "Create",
        "frontendUrl": null,
        "frontendSectionGroup": "adminCouponModule",
        "endpoint": '/api/admin/coupons/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Coupons",

    },

    // gallery
    gallery_albums: {
        "id": "gallery_albums",
        "name": "Gallery",
        "frontendUrl": '/admin/albums',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/',
        "HTTPMethod": null,
        "parent": null,
        "featureGroup": "Gallery",

    },



    created_album: {
        "id": "created_album",
        "name": "Create Album",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGalleryModule",
        "endpoint": '/api/admin/gallery/albums',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Gallery",

    },
    update_album: {
        "id": "update_album",
        "name": "Update Album",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGalleryModule",
        "endpoint": '/api/admin/gallery/albums',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Gallery",

    },
    delete_album: {
        "id": "delete_album",
        "name": "Update Album",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGalleryModule",
        "endpoint": '/api/admin/gallery/albums',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Gallery",

    },

    upload_gallery_image: {
        "id": "upload_gallery_image",
        "name": "Upload Image",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGalleryModule",
        "endpoint": '/api/admin/gallery/photos',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Gallery",

    },
    update_gallery_image: {
        "id": "update_gallery_image",
        "name": "Update Image",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGalleryModule",
        "endpoint": '/api/admin/gallery/photos',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Gallery",

    },
    delete_gallery_image: {
        "id": "delete_gallery_image",
        "name": "Delete Image",
        "frontendUrl": null,
        "frontendSectionGroup": "adminGalleryModule",
        "endpoint": '/api/admin/gallery/photos',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Gallery",

    },
    // cms
    cms: {
        "id": "cms",
        "name": "CMS",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/',
        "HTTPMethod": null,
        "parent": null,
        "featureGroup": "CMS",
    },
    'settings': {
        "id": "settings",
        "name": "General Settings",
        "frontendUrl": '/admin/cms/settings',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/cms/page',
        "HTTPMethod": 'get',
        "parent": 'cms',
        "featureGroup": "CMS",
    },
    'team': {
        "id": "team",
        "name": "Team",
        "frontendUrl": '/admin/cms/team',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/cms/team-members',
        "HTTPMethod": 'get',
        "parent": 'cms',
        "featureGroup": "CMS",
    },
    'terms_and_conditions': {
        "id": "terms_and_conditions",
        "name": "Terms And Conditions",
        "frontendUrl": '/admin/cms/terms-and-conditions',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/cms/page',
        "HTTPMethod": 'get',
        "parent": "cms",
        "featureGroup": "CMS",
    },
    'privacy_policy': {
        "id": "privacy_policy",
        "name": "Privacy Policy",
        "frontendUrl": '/admin/cms/privacy-policy',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/cms/page',
        "HTTPMethod": 'get',
        "parent": "cms",
        "featureGroup": "CMS",
    },
    'refund_policy': {
        "id": "refund_policy",
        "name": "Refund Policy",
        "frontendUrl": '/admin/cms/refund-policy',
        "frontendSectionGroup": "adminSidebar",
        "endpoint": '/api/admin/cms/page',
        "HTTPMethod": 'get',
        "parent": "cms",
        "featureGroup": "CMS",
    },
    'add_team_member': {
        "id": "add_team_member",
        "name": "Add Team Member",
        "frontendUrl": '',
        "frontendSectionGroup": "adminCMS",
        "endpoint": '/api/admin/cms/team-members',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "CMS",
    },
    'update_team_member': {
        "id": "update_team_member",
        "name": "Update Team Member",
        "frontendUrl": '',
        "frontendSectionGroup": "adminCMS",
        "endpoint": '/api/admin/cms/team-members/:id',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "CMS",
    },
    'reorder_team_members': {
        "id": "reorder_team_members",
        "name": "Reorder Team Members",
        "frontendUrl": '',
        "frontendSectionGroup": "adminCMS",
        "endpoint": '/api/admin/cms/team-members/re-order/members',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "CMS",
    },
    'remove_team_member': {
        "id": "remove_team_member",
        "name": "Remove Team Member",
        "frontendUrl": '',
        "frontendSectionGroup": "adminCMS",
        "endpoint": '/api/admin/cms/team-members/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "CMS",
    },
    // 'featured-instructors': {
    //     "id": "featured-instructors",
    //     "name": "Featured Instructors",
    //     "frontendUrl": '/admin/cms/featured-instructors',
    //     "frontendSectionGroup": "adminSidebar",
    //     "endpoint": '/',
    //     "HTTPMethod": 'get',
    //     "parent": 'cms',
    //     "featureGroup": "CMS",
    // },
    // 'add_featured_instructor': {
    //     "id": "add_featured_instructor",
    //     "name": "Add Featured Instructor",
    //     "frontendUrl": '',
    //     "frontendSectionGroup": "adminCMS",
    //     "endpoint": '/api/admin/cms/featured-instructors',
    //     "HTTPMethod": 'post',
    //     "parent": null,
    //     "featureGroup": "CMS",
    // },
    // 'reorder_featured_instructors': {
    //     "id": "reorder_featured_instructors",
    //     "name": "Reorder instructors",
    //     "frontendUrl": '',
    //     "frontendSectionGroup": "adminCMS",
    //     "endpoint": '/api/admin/cms/featured-instructors/order',
    //     "HTTPMethod": 'patch',
    //     "parent": null,
    //     "featureGroup": "CMS",
    // },
    // 'remove_featured_instructor': {
    //     "id": "remove_featured_instructor",
    //     "name": "Remove from Feature",
    //     "frontendUrl": '',
    //     "frontendSectionGroup": "adminCMS",
    //     "endpoint": '/api/admin/cms/featured-instructors/:id',
    //     "HTTPMethod": 'delete',
    //     "parent": null,
    //     "featureGroup": "CMS",
    // },
    'upsert_page_data': {
        "id": "upsert_page_data",
        "name": "Update Page",
        "frontendUrl": '',
        "frontendSectionGroup": "AdminCMS",
        "endpoint": ' /api/admin/cms/page',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "CMS",
    },




    //    'landing-page': {
    //         "id": "landing-page",
    //         "name": "Landing Page",
    //         "frontendUrl": '/admin/cms/landing-page',
    //         "frontendSectionGroup": "adminSidebar",
    //         "endpoint": '/',
    //         "HTTPMethod": 'get',
    //         "parent": 'cms',
    //         "featureGroup": "CMS",

    //     },

    // assignment
    get_assignments_with_stats: {
        "id": "get_assignments_with_stats",
        "name": "Assignments with submissions",
        "frontendUrl": null,
        "frontendSectionGroup": "adminAssignmentModule",
        "endpoint": '/api/admin/assignments/courses/:courseId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Assignment Submissions",

    },
    create_assignment: {
        "id": "create_assignment",
        "name": "Create Assignment",
        "frontendUrl": null,
        "frontendSectionGroup": "adminAssignmentModule",
        "endpoint": '/api/admin/assignments',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Course Content",

    },

    update_assignment: {
        "id": "update_assignment",
        "name": "Update Assignment",
        "frontendUrl": null,
        "frontendSectionGroup": "adminAssignmentModule",
        "endpoint": '/api/admin/assignments',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "Course Content",

    },
    delete_assignment: {
        "id": "delete_assignment",
        "name": "Delete Assignment",
        "frontendUrl": null,
        "frontendSectionGroup": "adminAssignmentModule",
        "endpoint": '/api/admin/assignments/:id',
        "HTTPMethod": 'delete',
        "parent": null,
        "featureGroup": "Course Content",

    },
    assignment_submissions_of_a_course: {
        "id": "assignment_submissions_of_a_course",
        "name": "Submission",
        "frontendUrl": null,
        "frontendSectionGroup": "adminAssignmentModule",
        "endpoint": '/api/admin/assignments/submissions/:assignmentId',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "Assignment Submissions",

    },
    evaluate_assignment: {
        "id": "evaluate_assignment",
        "name": "Evaluate",
        "frontendUrl": null,
        "frontendSectionGroup": "adminAssignmentModule",
        "endpoint": '/api/admin/assignments/evaluation',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "Assignment Submissions",

    }
    ,
    change_user_password_by_admin: {
        "id": "change_user_password_by_admin",
        "name": "Change Password",
        "frontendUrl": null,
        "frontendSectionGroup": "userManagementModule",
        "endpoint": '/api/admin/users/:userId/password',
        "HTTPMethod": 'patch',
        "parent": null,
        "featureGroup": "User Management",

    },
    // certificate 
    generate_certificate: {
        "id": "generate_certificate",
        "name": "Generate Certificate",
        "frontendUrl": null,
        "frontendSectionGroup": "userManagementModule",
        "endpoint": '/api/admin/course-certificates',
        "HTTPMethod": 'post',
        "parent": null,
        // "featureGroup": "User Management",

    },
    // SMS
    send_bulk_sms: {
        "id": "send_bulk_sms",
        "name": "SMS",
        "frontendUrl": '/admin/sms',
        "frontendSectionGroup": "adminHeaderNav",
        "endpoint": '/api/admin/sms',
        "HTTPMethod": 'post',
        "parent": null,
        "featureGroup": "SMS",

    },
    check_sms_balance: {
        "id": "check_sms_balance",
        "name": "SMS Balance",
        "frontendUrl": null,
        "frontendSectionGroup": "adminSmsModule",
        "endpoint": '/api/admin/sms/balance',
        "HTTPMethod": 'get',
        "parent": null,
        "featureGroup": "SMS",
    }

}
